// https://mholt.github.io/json-to-go/ で生成
package mi

import "time"

type AutoGenerated []struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	User      struct {
		ID                string `json:"id"`
		Name              any    `json:"name"`
		Username          string `json:"username"`
		Host              any    `json:"host"`
		AvatarURL         string `json:"avatarUrl"`
		AvatarBlurhash    any    `json:"avatarBlurhash"`
		AvatarDecorations []struct {
			ID  string `json:"id"`
			URL string `json:"url"`
		} `json:"avatarDecorations"`
		IsBot  bool `json:"isBot"`
		IsCat  bool `json:"isCat"`
		Emojis struct {
		} `json:"emojis"`
		OnlineStatus string `json:"onlineStatus"`
		BadgeRoles   []any  `json:"badgeRoles"`
	} `json:"user"`
	Type string `json:"type"`
	Note struct {
		ID        string    `json:"id"`
		CreatedAt time.Time `json:"createdAt"`
		UserID    string    `json:"userId"`
		User      struct {
			ID                string `json:"id"`
			Name              string `json:"name"`
			Username          string `json:"username"`
			Host              any    `json:"host"`
			AvatarURL         string `json:"avatarUrl"`
			AvatarBlurhash    string `json:"avatarBlurhash"`
			AvatarDecorations []any  `json:"avatarDecorations"`
			IsBot             bool   `json:"isBot"`
			IsCat             bool   `json:"isCat"`
			Emojis            struct {
			} `json:"emojis"`
			OnlineStatus string `json:"onlineStatus"`
			BadgeRoles   []any  `json:"badgeRoles"`
		} `json:"user"`
		Text               string `json:"text"`
		Cw                 any    `json:"cw"`
		Visibility         string `json:"visibility"`
		LocalOnly          bool   `json:"localOnly"`
		ReactionAcceptance string `json:"reactionAcceptance"`
		RenoteCount        int    `json:"renoteCount"`
		RepliesCount       int    `json:"repliesCount"`
		Reactions          struct {
			HayaHantei int `json:":haya_hantei@.:"`
		} `json:"reactions"`
		ReactionEmojis struct {
		} `json:"reactionEmojis"`
		FileIds      []any  `json:"fileIds"`
		Files        []any  `json:"files"`
		ReplyID      any    `json:"replyId"`
		RenoteID     any    `json:"renoteId"`
		ClippedCount int    `json:"clippedCount"`
		MyReaction   string `json:"myReaction"`
	} `json:"note,omitempty"`
	Note0 struct {
		ID        string    `json:"id"`
		CreatedAt time.Time `json:"createdAt"`
		UserID    string    `json:"userId"`
		User      struct {
			ID                string `json:"id"`
			Name              string `json:"name"`
			Username          string `json:"username"`
			Host              string `json:"host"`
			AvatarURL         string `json:"avatarUrl"`
			AvatarBlurhash    string `json:"avatarBlurhash"`
			AvatarDecorations []any  `json:"avatarDecorations"`
			IsBot             bool   `json:"isBot"`
			IsCat             bool   `json:"isCat"`
			Instance          struct {
				Name            string `json:"name"`
				SoftwareName    string `json:"softwareName"`
				SoftwareVersion string `json:"softwareVersion"`
				IconURL         string `json:"iconUrl"`
				FaviconURL      string `json:"faviconUrl"`
				ThemeColor      string `json:"themeColor"`
			} `json:"instance"`
			Emojis struct {
				Ta     string `json:"_ta"`
				I      string `json:"_i"`
				Ni     string `json:"_ni"`
				Xya    string `json:"_xya"`
				N      string `json:"_n"`
				Pu     string `json:"_pu"`
				Github string `json:"github"`
			} `json:"emojis"`
			OnlineStatus string `json:"onlineStatus"`
		} `json:"user"`
		Text               string `json:"text"`
		Cw                 any    `json:"cw"`
		Visibility         string `json:"visibility"`
		LocalOnly          bool   `json:"localOnly"`
		ReactionAcceptance any    `json:"reactionAcceptance"`
		RenoteCount        int    `json:"renoteCount"`
		RepliesCount       int    `json:"repliesCount"`
		Reactions          struct {
			NAMING_FAILED                     int `json:"🤯"`
			Sugoihanashi                      int `json:":sugoihanashi@.:"`
			SurprisedAi                       int `json:":surprised_ai@.:"`
			YosanoParty                       int `json:":yosano_party@.:"`
			IgyoNoKesin                       int `json:":igyo_no_kesin@.:"`
			Bikkuri9IneverseCom               int `json:":bikkuri@9ineverse.com:"`
			KokyakuGaHontouNiHituyoudattaMono int `json:":kokyaku_ga_hontou_ni_hituyoudatta_mono@.:"`
		} `json:"reactions"`
		ReactionEmojis struct {
			Bikkuri9IneverseCom string `json:"bikkuri@9ineverse.com"`
		} `json:"reactionEmojis"`
		Emojis struct {
		} `json:"emojis"`
		FileIds      []any    `json:"fileIds"`
		Files        []any    `json:"files"`
		ReplyID      string   `json:"replyId"`
		RenoteID     any      `json:"renoteId"`
		Mentions     []string `json:"mentions"`
		URI          string   `json:"uri"`
		ClippedCount int      `json:"clippedCount"`
		Reply        struct {
			ID        string    `json:"id"`
			CreatedAt time.Time `json:"createdAt"`
			UserID    string    `json:"userId"`
			User      struct {
				ID                string `json:"id"`
				Name              string `json:"name"`
				Username          string `json:"username"`
				Host              any    `json:"host"`
				AvatarURL         string `json:"avatarUrl"`
				AvatarBlurhash    string `json:"avatarBlurhash"`
				AvatarDecorations []struct {
					ID  string `json:"id"`
					URL string `json:"url"`
				} `json:"avatarDecorations"`
				IsBot  bool `json:"isBot"`
				IsCat  bool `json:"isCat"`
				Emojis struct {
				} `json:"emojis"`
				OnlineStatus string `json:"onlineStatus"`
				BadgeRoles   []struct {
					Name         string `json:"name"`
					IconURL      string `json:"iconUrl"`
					DisplayOrder int    `json:"displayOrder"`
				} `json:"badgeRoles"`
			} `json:"user"`
			Text               string `json:"text"`
			Cw                 any    `json:"cw"`
			Visibility         string `json:"visibility"`
			LocalOnly          bool   `json:"localOnly"`
			ReactionAcceptance any    `json:"reactionAcceptance"`
			RenoteCount        int    `json:"renoteCount"`
			RepliesCount       int    `json:"repliesCount"`
			Reactions          struct {
				SetsufuroCheering int `json:":setsufuro_cheering@.:"`
			} `json:"reactions"`
			ReactionEmojis struct {
			} `json:"reactionEmojis"`
			FileIds  []any    `json:"fileIds"`
			Files    []any    `json:"files"`
			ReplyID  string   `json:"replyId"`
			RenoteID any      `json:"renoteId"`
			Mentions []string `json:"mentions"`
		} `json:"reply"`
		MyReaction string `json:"myReaction"`
	} `json:"note,omitempty"`
	Note1 struct {
		ID        string    `json:"id"`
		CreatedAt time.Time `json:"createdAt"`
		UserID    string    `json:"userId"`
		User      struct {
			ID                string `json:"id"`
			Name              string `json:"name"`
			Username          string `json:"username"`
			Host              string `json:"host"`
			AvatarURL         string `json:"avatarUrl"`
			AvatarBlurhash    any    `json:"avatarBlurhash"`
			AvatarDecorations []any  `json:"avatarDecorations"`
			IsBot             bool   `json:"isBot"`
			IsCat             bool   `json:"isCat"`
			Instance          struct {
				Name            string `json:"name"`
				SoftwareName    string `json:"softwareName"`
				SoftwareVersion string `json:"softwareVersion"`
				IconURL         string `json:"iconUrl"`
				FaviconURL      string `json:"faviconUrl"`
				ThemeColor      string `json:"themeColor"`
			} `json:"instance"`
			Emojis struct {
			} `json:"emojis"`
			OnlineStatus string `json:"onlineStatus"`
		} `json:"user"`
		Text               string `json:"text"`
		Cw                 any    `json:"cw"`
		Visibility         string `json:"visibility"`
		LocalOnly          bool   `json:"localOnly"`
		ReactionAcceptance any    `json:"reactionAcceptance"`
		RenoteCount        int    `json:"renoteCount"`
		RepliesCount       int    `json:"repliesCount"`
		Reactions          struct {
			NAMING_FAILED      int `json:"👍"`
			Polarbear          int `json:":polarbear@.:"`
			WakaruMkYopoWork   int `json:":wakaru@mk.yopo.work:"`
			OtokuSocialSda1Net int `json:":otoku@social.sda1.net:"`
		} `json:"reactions"`
		ReactionEmojis struct {
			WakaruMkYopoWork   string `json:"wakaru@mk.yopo.work"`
			OtokuSocialSda1Net string `json:"otoku@social.sda1.net"`
		} `json:"reactionEmojis"`
		Emojis struct {
		} `json:"emojis"`
		FileIds      []any  `json:"fileIds"`
		Files        []any  `json:"files"`
		ReplyID      any    `json:"replyId"`
		RenoteID     any    `json:"renoteId"`
		URI          string `json:"uri"`
		URL          string `json:"url"`
		ClippedCount int    `json:"clippedCount"`
		MyReaction   string `json:"myReaction"`
	} `json:"note,omitempty"`
}
