CREATE TABLE "notes" ("note_id" VARCHAR NOT NULL, "reaction_id" VARCHAR NOT NULL, "user_id" VARCHAR NOT NULL, "reaction_emoji_name" VARCHAR NOT NULL, "text" VARCHAR, "created_at" TIMESTAMP, PRIMARY KEY ("note_id"), FOREIGN KEY ("reaction_emoji_name") REFERENCES "reactions" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION, FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
CREATE TABLE "users" ("user_id" VARCHAR NOT NULL, "name" VARCHAR, "display_name" VARCHAR, "avatar_url" VARCHAR, "count" INTEGER, PRIMARY KEY ("user_id"));
CREATE TABLE "reactions" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" VARCHAR NOT NULL, "image" VARCHAR, "is_symbol" BOOLEAN, "count" INTEGER, UNIQUE ("name"));
CREATE TABLE "hash_tags" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "text" VARCHAR, "count" INTEGER, UNIQUE ("text"));
CREATE TABLE "note_to_tags" ("note_id" VARCHAR NOT NULL, "hash_tag_id" INTEGER NOT NULL, PRIMARY KEY ("note_id", "hash_tag_id"), FOREIGN KEY ("hash_tag_id") REFERENCES "hash_tags" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, FOREIGN KEY ("note_id") REFERENCES "notes" ("note_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
CREATE TABLE "files" ("file_id" VARCHAR NOT NULL, "name" VARCHAR, "url" VARCHAR, "thumbnail_url" VARCHAR, "type" VARCHAR, "dominant_color" VARCHAR, "group_color" VARCHAR, "created_at" TIMESTAMP, PRIMARY KEY ("file_id"));
CREATE TABLE "note_to_files" ("note_id" VARCHAR NOT NULL, "file_id" VARCHAR NOT NULL, PRIMARY KEY ("note_id", "file_id"), FOREIGN KEY ("file_id") REFERENCES "files" ("file_id") ON UPDATE NO ACTION ON DELETE NO ACTION, FOREIGN KEY ("note_id") REFERENCES "notes" ("note_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
CREATE TABLE "months" ("ym" VARCHAR NOT NULL, "count" INTEGER, PRIMARY KEY ("ym"));
CREATE TABLE "days" ("ymd" VARCHAR NOT NULL, "ym" VARCHAR, "count" INTEGER, PRIMARY KEY ("ymd"), FOREIGN KEY ("ym") REFERENCES "months" ("ym") ON UPDATE NO ACTION ON DELETE NO ACTION);
