// Code generated by govalid; DO NOT EDIT.
package server

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*Job)(nil)

	// ErrNilJob is returned when the Job is nil.
	ErrNilJob = errors.New("input Job is nil")

	// ErrJobProfileRequiredValidation is returned when the Profile is required but not provided.
	ErrJobProfileRequiredValidation = govaliderrors.ValidationError{Reason: "field Profile is required", Path: "Job.Profile", Type: "required"}

	// ErrJobTypeRequiredValidation is returned when the Type is required but not provided.
	ErrJobTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field Type is required", Path: "Job.Type", Type: "required"}
)

func ValidateJobContext(ctx context.Context, t *Job) error {
	if t == nil {
		return ErrNilJob
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.Profile == "" {
		err := ErrJobProfileRequiredValidation
		err.Value = t.Profile
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.Type == 0 {
		err := ErrJobTypeRequiredValidation
		err.Value = t.Type
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateJob(t *Job) error {
	return ValidateJobContext(context.Background(), t)
}

func (t *Job) Validate() error {
	return ValidateJob(t)
}

func (t *Job) ValidateContext(ctx context.Context) error {
	return ValidateJobContext(ctx, t)
}
